#%RAML 1.0 DataType
type: object
properties:
  movieId?: integer
  movieName: string
  movieDescription: string
  cityName: string
  Language: string
  RunningLength: string
  ratings: string
  genre: string