#%RAML 1.0 NamedExample
value:
  -
    movieId: 1
    movieName: "Laxmi Bomb"
    movieDescription: "Horror Movie"
    cityName: "Mumbai"
    Language: "Hindi"
    RunningLength: "144 minutes"
    ratings: "4"
    genre: "Horror"