#%RAML 1.0 NamedExample
value:
  -
    movieId: 1
    movieName: "Laxmi Bomb"
    movieDescription: "Horror Movie"
    cityName: "Mumbai"
    Language: "Hindi"
    RunningLength: "144 minutes"
    ratings: "4"
    genre: "Horror"
  -
    movieId: 2
    movieName: "Thappad"
    movieDescription: "Drama Movie"
    cityName: "Mumbai"
    Language: "Telugu"
    RunningLength: "150 minutes"
    ratings: "4"
    genre: "Drama"