#%RAML 1.0 NamedExample
value:
  -
    theatreName: "Wave Cinemas"
    ratings: "5.0"
    cityName: "Mumbai"
    genre: "Action, Sci-Fi"
    movieId: 3
    language: "English"
    RunningLength: "148 Minutes"
    theatreId: 1
    movieDescription: "No Way Home"
    movieName: "Spider-Man"
  -
    theatreName: "Wave Cinemas"
    ratings: "5.0"
    cityName: "Mumbai"
    genre: "Action, Sci-Fi"
    movieId: 3
    language: "English"
    RunningLength: "148 Minutes"
    theatreId: 1
    movieDescription: "No Way Home"
    movieName: "Spider-Man"